{
 "title": "Consumer Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Consumed Messages By Pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (consumer_processed_messages_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Consumer Restarts",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(consumer_restarts_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer Database Connection Retries By Pod",
   "type": "stat",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (consumer_database_connection_retries_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}