autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85

podDisruptionBudget:
  minAvailable: 1

resources:
  requests:
    cpu: 100m
    memory: 90Mi
  limits:
    cpu: 200m
    memory: 200Mi

serviceAccount:
  create: true
  automountServiceAccountToken: true

rbac:
  create: true
