cluster-autoscaler:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi
  image:
    repository: marlapativ/cluster-autoscaler
    tag: v1.30.0
  podDisruptionBudget:
    maxUnavailable: 0

serviceAccount:
  create: true
  automountServiceAccountToken: true
