istio:
  monitoring:
    namespace: 'istio-system'
    namespaceSelector:
      any: true
  gateway:
    namespace: 'istio-system'
    virtualservice:
      hosts:
        - ${domain}
      tls:
        - match:
            - port: 443
              sniHosts:
                - ${domain}
          route:
            - destination:
                host: grafana.operations.svc.cluster.local
                port:
                  number: 3000

certmanager:
  namespace: 'operations'
  email:
    - ${email}
  # staging: false

certificate:
  dnsNames:
    - ${domain}
