controllerManager:
  manager:
    image:
      repository: marlapativ/cve-operator
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
  serviceAccount:
    automountServiceAccountToken: true
pdb:
  create: true
  minAvailable: 1
  maxUnavailable: {}

autoscaling:
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 85
    targetMemory: 85
