controllerManager:
  manager:
    image:
      repository: marlapativ/cve-operator
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
